# Generated by Django 3.0.7 on 2020-09-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='listing',
            name='winner',
            field=models.CharField(default='', max_length=64),
        ),
    ]
