# Generated by Django 2.2.7 on 2020-09-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200904_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='city',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='code',
        ),
    ]
