# Generated by Django 3.0.7 on 2020-09-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200904_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('initial_amt', models.IntegerField()),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.RenameModel(
            old_name='bids',
            new_name='bid',
        ),
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
        migrations.DeleteModel(
            name='listings',
        ),
    ]
