# Generated by Django 3.0.7 on 2020-09-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200908_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='1', upload_to='product'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='initial_amt',
            field=models.IntegerField(default='1'),
        ),
    ]
