# Generated by Django 3.0.7 on 2020-09-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200909_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='initial_amt',
            field=models.IntegerField(),
        ),
    ]
