# Generated by Django 3.0.7 on 2020-09-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200910_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('1', 'Fashion'), ('2', 'Toys'), ('3', 'Electronics'), ('4', 'Home'), ('5', 'Edible')], max_length=20),
        ),
    ]
