# Generated by Django 3.0.7 on 2020-09-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
